// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT0NA32GuSnE4zosEMa9QHo7ZeGSwKsgU',
    appId: '1:304821041286:web:e5f99faf263ec667a9f907',
    messagingSenderId: '304821041286',
    projectId: 'ecom-wala',
    authDomain: 'ecom-wala.firebaseapp.com',
    storageBucket: 'ecom-wala.firebasestorage.app',
    measurementId: 'G-DWHLRSP5L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-WLMWRaLPwXHXLOJgxBuNTf8lmcNqAW4',
    appId: '1:304821041286:android:44579ad0786016fea9f907',
    messagingSenderId: '304821041286',
    projectId: 'ecom-wala',
    storageBucket: 'ecom-wala.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfTvcK0agfccaxdQtFDKbF6W2CoT8LeVc',
    appId: '1:304821041286:ios:ceaf9860ee70bad3a9f907',
    messagingSenderId: '304821041286',
    projectId: 'ecom-wala',
    storageBucket: 'ecom-wala.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfTvcK0agfccaxdQtFDKbF6W2CoT8LeVc',
    appId: '1:304821041286:ios:ceaf9860ee70bad3a9f907',
    messagingSenderId: '304821041286',
    projectId: 'ecom-wala',
    storageBucket: 'ecom-wala.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT0NA32GuSnE4zosEMa9QHo7ZeGSwKsgU',
    appId: '1:304821041286:web:ff7fcef6200d009aa9f907',
    messagingSenderId: '304821041286',
    projectId: 'ecom-wala',
    authDomain: 'ecom-wala.firebaseapp.com',
    storageBucket: 'ecom-wala.firebasestorage.app',
    measurementId: 'G-6ZR098Y1XC',
  );
}
